'use client';

import { motion } from 'framer-motion';
import { C, EO, WRAP, LABEL } from '@/lib/design';

function Reveal({ children, delay = 0, y = 28 }: { children: React.ReactNode; delay?: number; y?: number }) {
  return (
    <motion.div initial={{ opacity: 0, y }} whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true, margin: '-40px' }} transition={{ ...EO, delay }}>
      {children}
    </motion.div>
  );
}

const HR = () => <div style={{ height: 1, background: C.warm2, margin: 0 }} />;

const LAST_UPDATED = 'March 15, 2026';

export default function TermsPage() {
  return (
    <div style={{ background: C.cream, minHeight: '100vh', fontFamily: "'DM Sans', sans-serif" }}>

      {/* ═══ Hero ═══ */}
      <section>
        <div style={{ ...WRAP, paddingTop: 48, paddingBottom: 48 }} className="section-pad">
          <Reveal>
            <span style={LABEL}>Legal</span>
            <h1 style={{
              fontFamily: "'Bricolage Grotesque', sans-serif",
              fontSize: 'clamp(44px, 6vw, 72px)',
              fontWeight: 900, color: C.ink,
              letterSpacing: '-0.04em', lineHeight: 1.0, marginBottom: 16,
            }}>
              Terms of Service
            </h1>
            <p style={{ fontSize: 13, color: C.muted, fontFamily: 'monospace', letterSpacing: '0.04em' }}>
              Last updated: {LAST_UPDATED}
            </p>
          </Reveal>
        </div>
      </section>

      <HR />

      {/* ═══ Sections ═══ */}
      {[
        {
          title: '1. Acceptance of Terms',
          content: [
            'By accessing or using ConvoCoach ("the Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, do not use the Service.',
            'We reserve the right to modify these terms at any time. Continued use of the Service after changes constitutes acceptance of the new terms.',
          ],
        },
        {
          title: '2. Description of Service',
          content: [
            'ConvoCoach is an AI-powered conversation analysis tool that processes screenshots of text conversations to provide behavioral analysis, signal detection, and suggested responses.',
            'The Service also includes Practice Mode, which allows users to engage in simulated conversations with AI personalities for communication skill development.',
            'Analysis results are generated by artificial intelligence and should be considered informational, not professional relationship advice.',
          ],
        },
        {
          title: '3. User Accounts',
          content: [
            'You may use certain features without creating an account. Creating an account (via Google OAuth) provides access to additional features including analysis history and personalized settings.',
            'You are responsible for maintaining the security of your account. You agree to notify us immediately of any unauthorized access.',
            'You must be at least 16 years old to use this Service.',
          ],
        },
        {
          title: '4. Acceptable Use',
          content: [
            'You agree to use the Service only for lawful purposes and in accordance with these Terms.',
            'You agree not to upload screenshots containing content that is illegal, threatening, harassing, defamatory, or otherwise objectionable.',
            'You agree not to attempt to reverse-engineer, decompile, or otherwise extract the source code of the Service.',
            'You agree not to use the Service to stalk, harass, or intimidate any person.',
            'You agree not to use automated tools (bots, scrapers) to access the Service without our written permission.',
          ],
        },
        {
          title: '5. Intellectual Property',
          content: [
            'The Service, including all content, features, and functionality, is owned by ConvoCoach and protected by copyright, trademark, and other intellectual property laws.',
            'Your uploaded screenshots remain your property. By uploading, you grant us a limited, temporary license to process the image for the sole purpose of generating your analysis. This license expires when the screenshot is deleted (within 60 seconds).',
            'Analysis results generated by our AI are provided to you for personal use. You may not resell or redistribute analysis outputs as a commercial service.',
          ],
        },
        {
          title: '6. Subscriptions & Payments',
          content: [
            'ConvoCoach offers free and premium subscription tiers. Free tier includes limited analyses per month.',
            'Premium subscriptions are billed monthly or annually as selected at checkout. Payments are processed securely via Stripe.',
            'You may cancel your subscription at any time from your account settings. Cancellation takes effect at the end of the current billing period. No partial refunds are provided for unused time.',
            'We reserve the right to modify pricing with 30 days notice to existing subscribers.',
          ],
        },
        {
          title: '7. Disclaimer of Warranties',
          content: [
            'The Service is provided "as is" and "as available" without warranties of any kind, either express or implied.',
            'We do not guarantee the accuracy, completeness, or usefulness of any analysis results. AI-generated insights are probabilistic assessments, not definitive evaluations.',
            'We do not guarantee uninterrupted or error-free operation of the Service.',
          ],
        },
        {
          title: '8. Limitation of Liability',
          content: [
            'To the fullest extent permitted by law, ConvoCoach shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Service.',
            'Our total liability for any claim arising from these Terms or the Service is limited to the amount you paid us in the 12 months preceding the claim, or $100, whichever is greater.',
          ],
        },
        {
          title: '9. Termination',
          content: [
            'We may suspend or terminate your access to the Service at any time for violation of these Terms, without prior notice.',
            'You may delete your account at any time from your settings page. Upon deletion, all associated data will be permanently removed within 30 days.',
          ],
        },
        {
          title: '10. Contact',
          content: [
            'For questions about these Terms, contact us at legal@convocoach.ai.',
          ],
        },
      ].map(({ title, content }, i) => {
        const isDark = i % 2 !== 0;
        return (
          <div key={title}>
            <section style={{ background: isDark ? C.ink : C.cream }}>
              <div style={WRAP} className="section-pad">
                <Reveal>
                  <h2 style={{
                    fontFamily: "'Bricolage Grotesque', sans-serif",
                    fontSize: 'clamp(22px, 3vw, 32px)',
                    fontWeight: 900, color: isDark ? C.cream : C.ink,
                    letterSpacing: '-0.02em', lineHeight: 1.15, marginBottom: 24,
                  }}>
                    {title}
                  </h2>
                </Reveal>
                <Reveal delay={0.06}>
                  <ul style={{ maxWidth: 640, paddingLeft: 0, listStyle: 'none', margin: 0, display: 'flex', flexDirection: 'column', gap: 14 }}>
                    {content.map((item, j) => (
                      <li key={j} style={{ display: 'flex', alignItems: 'flex-start', gap: 12 }}>
                        <span style={{ width: 5, height: 5, borderRadius: '50%', background: isDark ? `${C.cream}20` : C.warm2, display: 'block', flexShrink: 0, marginTop: 8 }} />
                        <p style={{
                          fontSize: 14, color: isDark ? `${C.cream}55` : C.muted,
                          lineHeight: 1.75, margin: 0,
                        }}>{item}</p>
                      </li>
                    ))}
                  </ul>
                </Reveal>
              </div>
            </section>
            {i < 9 && <HR />}
          </div>
        );
      })}
    </div>
  );
}
